export const selectedWinnerOverrides: Record<string, string> = {
  "Ashish Ghimire": "France",
  "Manish Poudel": "Germany",
  "Sarmila Basnet": "Argentina",
  "Kushal Gautam": "Brazil",
  "Yogesh Banskota": "Spain",
  "Uttam Acharya": "Spain",
  "Ujjwal Maharjan": "Spain",
  "Srijana Shrestha": "Portugal",
  "Subhesh Chandra Baral": "France",
  "Lois Thapa": "Portugal",
  "Saru Adhikari": "France",
  "Ashish Shrestha": "Portugal",
  "Binita Thapa Magar": "Portugal",
  "Karan Nepali": "Portugal",
  "Ujjal Paudel": "France",
  "Samin Singh Bhandari": "Argentina",
  "Sumit Sinha": "Brazil",
  "Suman Karmacharya": "Brazil",
  "Sumana Adhikari": "Spain",
  "Sanjay Sundas": "Argentina",
  "Yagya Bahadur Raut": "Portugal",
  "Nira Shah": "Portugal",
  "Utsha Thapa": "Portugal",
  "Paras Mani Pokhrel": "Spain",
  "Sudesh Maharjan": "Spain",
  "Sudip Bohara": "Argentina",
  "Binod Maharjan": "Portugal",
  "Om Prakash Mishra": "Argentina",
  "Bijay Karki": "Argentina",
  "Gokul Kushmi": "France",
  "Chet Kumar Rawal": "France",
  "Sabita Bohara": "France",
  "Nirnjan Regmi": "France",
  "Ganga Rimal": "Brazil",
  "Jaison Maharjan": "Spain",
  "Bal Krishna Lamsal": "Portugal",
  "Khushi Regmi": "Argentina",
  "Menuka Paudel": "France",
  "Prajwal Neupane": "Spain",
  "Shraddha Khanal": "France",
  "Akkshita Bhandari": "Spain",
  "Biraj Dhakal": "Germany",
  "Shreejal Manandhar": "Argentina",
  "Uma Rai": "Argentina",
  "Atish Gurung": "Argentina",
  "Umesh Budhathoki": "Brazil",
  "Pasang Yonjan": "Netherlands",
  "Khemraj Ojha": "France",
  "Ashish Gyawali": "England",
  "Manoj Khakurel": "Brazil",
  "Rajiv Gurbacharya": "Spain",
  "Rachana Adhikari": "France",
  "Geeta Basnet": "Spain",
  "Yubraj Paudel": "Argentina",
  "Upadesh Shakya": "Spain",
  "Bibek Gurung": "Germany",
  "Rekha Bhattarai": "Argentina",
  "Jayandra Dangol": "Spain",
  "Prapti Chand": "Portugal",
  "Neelu Khadka": "Spain",
  "Pramesh Regmi": "Spain",
  "Prabesh Pyakurel": "Spain",
  "Dilli Prasad Acharya": "Spain",
  "Min Bahadur Thapa": "France",
  "Lucy Joshi": "Spain",
  "Roshana Khanal": "Portugal",
  "Bibek Gautam": "England",
  "Pharshu Ram Marasini": "France",
  "Arun Chaudhary": "Brazil",
  "Anish Baniya": "Spain",
  "Sandip Gautam": "Spain",
  "Basanta Poudel": "England",
  "Rajesh Khadka": "England",
  "Sumana Karki": "Netherlands",
  "Prakash Bikram Khatri": "Portugal",
  "Shreeja Dhungel": "Spain",
  "Yubraj Ghimire": "Brazil",
  "Kabi Raj Dahal": "Portugal",
  "Ramesh K.C.": "Argentina",
  "Sunil Giri": "Brazil",
  "Umesh Prasad Mainali": "Brazil",
  "Paharam Chaudhary": "France",
  "Bibek Tripathi": "Spain",
  "Jayaram Dhungana": "Portugal",
  "Bishnu Prasad Gouli": "Portugal",
  "Suresh Raj Joshi": "Brazil",
  "Sajan Khatri": "Portugal",
  "Jaganath Karki": "Portugal",
  "Santosh Gyawali": "Netherlands",
  "Khem Bahadur Gharti": "Argentina",
  "Prajwal Simkhada": "Portugal",
  "Dharma Raj Adhikari": "Argentina",
  "Krishna Prasad Khanal": "France",
};
